version: "3.0"

services:
  torchserve:
    image: pytorch/torchserve:0.8.1-gpu
    container_name: torchserve-latest
    runtime: nvidia
    restart: always
    volumes:
      - ts-test:/usr/local/couture/trained-models
      - ./ts.config:/usr/local/couture/trained-models/pytorch-models/ts.config
    ports:
      - "8780:8080"
      - "8781:8081"
    networks:
      - serving-network
    command: "python3 -m pip install --upgrade pip && torchserve --start --ts-config /usr/local/couture/trained-models/pytorch-models/ts.config --models all"
    shm_size: '2gb'

networks:
  serving-network:
    external: true
volumes:
  ts-test:
    external: true
